"""
This type stub file was generated by pyright.
"""

from frappe.website.page_renderers.template_page import TemplatePage

class ListPage(TemplatePage):
	def can_render(self): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
		...
	
	def render(self): # -> Response:
		...
	


