"""
This type stub file was generated by pyright.
"""

import frappe
from collections.abc import Iterable
from typing import TYPE_CHECKING
from frappe.core.doctype.communication.communication import Communication

if TYPE_CHECKING:
	...
@frappe.whitelist()
def make(doctype=..., name=..., content=..., subject=..., sent_or_received=..., sender=..., sender_full_name=..., recipients=..., communication_medium=..., send_email=..., print_html=..., print_format=..., attachments=..., send_me_a_copy=..., cc=..., bcc=..., read_receipt=..., print_letterhead=..., email_template=..., communication_type=..., send_after=..., print_language=..., now=..., **kwargs) -> dict[str, str]:
	"""Make a new communication. Checks for email permissions for specified Document.

	:param doctype: Reference DocType.
	:param name: Reference Document name.
	:param content: Communication body.
	:param subject: Communication subject.
	:param sent_or_received: Sent or Received (default **Sent**).
	:param sender: Communcation sender (default current user).
	:param recipients: Communication recipients as list.
	:param communication_medium: Medium of communication (default **Email**).
	:param send_email: Send via email (default **False**).
	:param print_html: HTML Print format to be sent as attachment.
	:param print_format: Print Format name of parent document to be sent as attachment.
	:param attachments: List of File names or dicts with keys "fname" and "fcontent"
	:param send_me_a_copy: Send a copy to the sender (default **False**).
	:param email_template: Template which is used to compose mail .
	:param send_after: Send after the given datetime.
	"""
	...

def validate_email(doc: Communication) -> None:
	"""Validate Email Addresses of Recipients and CC"""
	...

def set_incoming_outgoing_accounts(doc): # -> None:
	...

def add_attachments(name: str, attachments: Iterable[str | dict]) -> None:
	"""Add attachments to the given Communication

	:param name: Communication name
	:param attachments: File names or dicts with keys "fname" and "fcontent"
	"""
	...

@frappe.whitelist(allow_guest=True, methods=("GET", ))
def mark_email_as_seen(name: str | None = ...): # -> None:
	...

def update_communication_as_read(name): # -> None:
	...

