repos:
    - repo: https://github.com/psf/black
      rev: 25.9.0
      hooks:
          - id: black
            exclude: ^typings/

    - repo: https://github.com/pycqa/isort
      rev: 6.0.1
      hooks:
          - id: isort
            exclude: ^typings/

    - repo: https://github.com/pycqa/flake8
      rev: 7.3.0
      hooks:
          - id: flake8
            exclude: ^typings/

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.36.0
      hooks:
          - id: eslint
            files: \.(js|ts|jsx|tsx)$
            exclude: ^typings/

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            exclude: ^typings/
