"""
This type stub file was generated by pyright.
"""

"""
Sync's doctype and docfields from txt files to database
perms will get synced only if none exist
"""
IMPORTABLE_DOCTYPES = ...
def sync_all(force=..., reset_permissions=...): # -> None:
	...

def sync_for(app_name, force=..., reset_permissions=...): # -> None:
	...

def get_doc_files(files, start_path): # -> list[Any]:
	"""walk and sync all doctypes and pages"""
	...

def remove_orphan_doctypes(): # -> None:
	"""Find and remove any orphaned doctypes.

	These are doctypes for which code and schema file is
	deleted but entry is present in DocType table.

	Note: Deleting the entry doesn't delete any data.
	So this is supposed to be non-destrictive operation.
	"""
	...

