"""
This type stub file was generated by pyright.
"""

import frappe
from typing import TYPE_CHECKING, Union
from frappe.model.document import Document
from frappe.workflow.doctype.workflow.workflow import Workflow

if TYPE_CHECKING:
	...
DEFAULT_WORKFLOW_TASKS = ...
class WorkflowStateError(frappe.ValidationError):
	...


class WorkflowTransitionError(frappe.ValidationError):
	...


class WorkflowPermissionError(frappe.ValidationError):
	...


def get_workflow_name(doctype): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | Any | None:
	...

@frappe.whitelist()
def get_transitions(doc: Union[Document, str, dict], workflow: Workflow = ..., raise_exception: bool = ...) -> list[dict]:
	"""Return list of possible transitions for the given doc"""
	...

def get_workflow_safe_globals(): # -> dict[str, _dict[Any, SessionType]]:
	...

def is_transition_condition_satisfied(transition, doc) -> bool:
	...

@frappe.whitelist()
def apply_workflow(doc, action): # -> _SingleDocument | None:
	"""Allow workflow action on the current doc"""
	...

@frappe.whitelist()
def can_cancel_document(doctype): # -> bool:
	...

def validate_workflow(doc): # -> None:
	"""Validate Workflow State and Transition for the current user.

	- Check if user is allowed to edit in current state
	- Check if user is allowed to transition to the next state (if changed)
	"""
	...

def get_workflow(doctype) -> Workflow:
	...

def has_approval_access(user, doc, transition):
	...

def get_workflow_state_field(workflow_name): # -> Any:
	...

def send_email_alert(workflow_name): # -> Any:
	...

def get_workflow_field_value(workflow_name, field): # -> Any:
	...

@frappe.whitelist()
def bulk_workflow_approval(docnames, doctype, action): # -> None:
	...

def print_workflow_log(messages, title, doctype, indicator): # -> None:
	...

@frappe.whitelist()
def get_common_transition_actions(docs, doctype): # -> list[Any] | list[Any | None]:
	...

def show_progress(docnames, message, i, description): # -> None:
	...

def set_workflow_state_on_action(doc, workflow_name, action): # -> None:
	...

