"""
This type stub file was generated by pyright.
"""

REDIS_KEYS = ...
def is_open(scheme, hostname, port, path, timeout=...): # -> bool:
	...

def check_database(): # -> dict[str, bool] | dict[Any, bool] | dict[Any | str, bool]:
	...

def check_redis(redis_services=...): # -> dict[Any, Any]:
	...

def check_connection(redis_services=...): # -> dict[Any, Any]:
	...

