"""
This type stub file was generated by pyright.
"""

from typing import Literal

def get_print(
    doctype=...,
    name=...,
    print_format=...,
    style=...,
    as_pdf=...,
    doc=...,
    output=...,
    no_letterhead=...,
    password=...,
    pdf_options=...,
    letterhead=...,
    pdf_generator: Literal["wkhtmltopdf", "chrome"] | None = ...,
):  # -> str | PdfWriter | bytes:
    """Get Print Format for given document.
    :param doctype: DocType of document.
    :param name: Name of document.
    :param print_format: Print Format name. Default 'Standard',
    :param style: Print Format style.
    :param as_pdf: Return as PDF. Default False.
    :param password: Password to encrypt the pdf with. Default None
    :param pdf_generator: PDF generator to use. Default 'wkhtmltopdf'
    """
    ...

def attach_print(
    doctype,
    name,
    file_name=...,
    print_format=...,
    style=...,
    html=...,
    doc=...,
    lang=...,
    print_letterhead=...,
    password=...,
    letterhead=...,
):  # -> dict[str, Any]:
    ...
