"""
This type stub file was generated by pyright.
"""

import datetime
from typing import TYPE_CHECKING
from werkzeug.wrappers import Response

if TYPE_CHECKING:
	...
DateOrTimeTypes = datetime.date | datetime.datetime | datetime.time
timedelta = datetime.timedelta
def report_error(status_code): # -> Response:
	"""Build error. Show traceback in developer mode"""
	...

def is_traceback_allowed(): # -> bool | Any | Literal[0] | None:
	...

def build_response(response_type=...): # -> Response:
	...

def as_csv(): # -> Response:
	...

def as_txt(): # -> Response:
	...

def as_raw(): # -> Response:
	...

def as_json(): # -> Response:
	...

def as_pdf(): # -> Response:
	...

def as_binary(): # -> Response:
	...

def make_logs(): # -> None:
	"""make strings for msgprint and errprint"""
	...

def json_handler(obj): # -> str | list[Any] | float:
	"""serialize non-serializable data for json"""
	...

def as_page(): # -> Response:
	"""print web page"""
	...

def redirect(): # -> Response:
	...

def download_backup(path): # -> Response:
	...

def download_private_file(path: str) -> Response:
	"""Checks permissions and sends back private file"""
	...

def send_private_file(path: str) -> Response:
	...

def handle_session_stopped(): # -> Response:
	...

