"""
This type stub file was generated by pyright.
"""

from frappe.utils.caching import site_cache

"""Basic telemetry for improving apps.

WARNING: Everything in this file should be treated "internal" and is subjected to change or get
removed without any warning.
"""
POSTHOG_PROJECT_FIELD = ...
POSTHOG_HOST_FIELD = ...
def add_bootinfo(bootinfo): # -> None:
	...

@site_cache(ttl=60 * 60 * 12)
def site_age(): # -> int | None:
	...

def init_telemetry(): # -> None:
	"""Init posthog for server side telemetry."""
	...

def flush_telemetry(): # -> None:
	...

def capture(event, app, **kwargs): # -> None:
	...

def capture_doc(doc, action): # -> None:
	...

