"""
This type stub file was generated by pyright.
"""

import frappe

@frappe.whitelist()
def download_pdf(doctype, name, print_format, letterhead=...):  # -> None:
    ...
def get_html(doctype, name, print_format, letterhead=...):  # -> str | Any | None:
    ...

class PrintFormatGenerator:
    """
    Generate a PDF of a Document, with repeatable header and footer if letterhead is provided.

    This generator draws its inspiration and, also a bit of its implementation, from this
    discussion in the library github issues: https://github.com/Kozea/WeasyPrint/issues/92
    """
    def __init__(self, print_format, doc, letterhead=...) -> None:
        """
        Parameters
        ----------
        print_format: str
                Name of the Print Format
        doc: str
                Document to print
        letterhead: str
                Letter Head to apply (optional)
        """
        ...

    def build_context(self):  # -> None:
        ...
    def get_html_preview(self):  # -> str | Any | None:
        ...
    def get_main_html(self):  # -> str | Any | None:
        ...
    def get_header_footer_html(self):  # -> tuple[str | Any | None, str | Any | None]:
        ...
    def render_pdf(self):
        """Return a bytes sequence of the rendered PDF."""
        ...

    def get_layout(self, print_format):  # -> str:
        ...
    def set_field_renderers(self, layout): ...
    def process_margin_texts(self, layout): ...
    @staticmethod
    def get_element(boxes, element):  # -> None:
        """
        Given a set of boxes representing the elements of a PDF page in a DOM-like way, find the
        box which is named `element`.

        Look at the notes of the class for more details on Weasyprint insides.
        """
        ...

def import_weasyprint():  # -> tuple[Any, Any] | None:
    ...
