"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

BLOCKED_DOCTYPES = ...

class DataImport(Document):
    if TYPE_CHECKING:
        custom_delimiters: DF.Check
        delimiter_options: DF.Data | None
        google_sheets_url: DF.Data | None
        import_file: DF.Attach | None
        import_type: DF.Literal["", "Insert New Records", "Update Existing Records"]
        mute_emails: DF.Check
        payload_count: DF.Int
        reference_doctype: DF.Link
        show_failed_logs: DF.Check
        status: DF.Literal[Pending, Success, "Partial Success", Error, "Timed Out"]
        submit_after_import: DF.Check
        template_options: DF.Code | None
        template_warnings: DF.Code | None
        use_csv_sniffer: DF.Check
        ...
    def validate(self):  # -> None:
        ...
    def set_delimiters_flag(self):  # -> None:
        ...
    def validate_doctype(self):  # -> None:
        ...
    def validate_import_file(self):  # -> None:
        ...
    def validate_google_sheets_url(self):  # -> None:
        ...
    def set_payload_count(self):  # -> None:
        ...
    @frappe.whitelist()
    def get_preview_from_template(self, import_file=..., google_sheets_url=...):  # -> _dict[Any, Any] | None:
        ...
    def start_import(self):  # -> bool:
        ...
    def export_errored_rows(self):  # -> None:
        ...
    def download_import_log(self):  # -> None:
        ...
    def get_importer(self):  # -> Importer:
        ...
    def on_trash(self):  # -> None:
        ...

@frappe.whitelist()
def get_preview_from_template(
    data_import: str, import_file: str | None = ..., google_sheets_url: str | None = ...
):  # -> _dict[Any, Any] | None:
    ...
@frappe.whitelist()
def form_start_import(data_import: str):  # -> bool:
    ...
def start_import(data_import):  # -> None:
    """This method runs in background job"""
    ...

@frappe.whitelist()
def download_template(
    doctype, export_fields=..., export_records=..., export_filters=..., file_type=...
):  # -> None:
    """
    Download template from Exporter
            :param doctype: Document Type
            :param export_fields=None: Fields to export as dict {'Sales Invoice': ['name', 'customer'], 'Sales Invoice Item': ['item_code']}
            :param export_records=None: One of 'all', 'by_filter', 'blank_template'
            :param export_filters: Filter dict
            :param file_type: File type to export into
    """
    ...

@frappe.whitelist()
def download_errored_template(data_import_name: str):  # -> None:
    ...
@frappe.whitelist()
def download_import_log(data_import_name: str):  # -> None:
    ...
@frappe.whitelist()
def get_import_status(data_import_name: str):  # -> dict[str, str]:
    ...
@frappe.whitelist()
def get_import_logs(data_import: str):  # -> list[Any]:
    ...
def import_file(doctype, file_path, import_type, submit_after_import=..., console=...):  # -> None:
    """
    Import documents in from CSV or XLSX using data import.

    :param doctype: DocType to import
    :param file_path: Path to .csv, .xls, or .xlsx file to import
    :param import_type: One of "Insert" or "Update"
    :param submit_after_import: Whether to submit documents after import
    :param console: Set to true if this is to be used from command line. Will print errors or progress to stdout.
    """
    ...

def import_doc(path, pre_process=..., sort=...):  # -> None:
    ...
def export_json(doctype, path, filters=..., or_filters=..., name=..., order_by=...):  # -> None:
    ...
def export_csv(doctype, path):  # -> None:
    ...
