"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class UserSelectDocumentType(Document):
    if TYPE_CHECKING:
        document_type: DF.Link
        parent: DF.Data
        parentfield: DF.Data
        parenttype: DF.Data
        ...
