"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class NotificationRecipient(Document):
    if TYPE_CHECKING:
        bcc: DF.Code | None
        cc: DF.Code | None
        condition: DF.Data | None
        parent: DF.Data
        parentfield: DF.Data
        parenttype: DF.Data
        receiver_by_document_field: DF.Literal[None]
        receiver_by_role: DF.Link | None
        ...
