"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from pypika.queries import QueryBuilder, Table
from pypika.terms import AggregateFunction, Term
from frappe.database.utils import FilterValue
from frappe.query_builder import Criterion, Field

if TYPE_CHECKING:
	...
TAB_PATTERN = ...
WORDS_PATTERN = ...
COMMA_PATTERN = ...
TABLE_NAME_PATTERN = ...
ALLOWED_FIELD_PATTERN = ...
FIELD_PARSE_REGEX = ...
FUNCTION_MAPPING = ...
class Engine:
	def get_query(self, table: str | Table, fields: str | list | tuple | None = ..., filters: dict[str, FilterValue] | FilterValue | list[list | FilterValue] | None = ..., order_by: str | None = ..., group_by: str | None = ..., limit: int | None = ..., offset: int | None = ..., distinct: bool = ..., for_update: bool = ..., update: bool = ..., into: bool = ..., delete: bool = ..., *, validate_filters: bool = ..., skip_locked: bool = ..., wait: bool = ..., ignore_permissions: bool = ..., user: str | None = ..., parent_doctype: str | None = ...) -> QueryBuilder:
		...
	
	def validate_doctype(self): # -> None:
		...
	
	def apply_fields(self, fields): # -> None:
		...
	
	def apply_filters(self, filters: dict[str, FilterValue] | FilterValue | list[list | FilterValue] | None = ...): # -> None:
		...
	
	def apply_list_filters(self, filter: list): # -> None:
		...
	
	def apply_dict_filters(self, filters: dict[str, FilterValue | list]): # -> None:
		...
	
	def parse_string_field(self, field: str): # -> Star | Any:
		"""
		Parses a field string into a pypika Field object.

		Handles:
		- *
		- simple_field
		- `quoted_field`
		- tabDocType.simple_field
		- `tabDocType`.`quoted_field`
		- `tabTable Name`.`quoted_field`
		- Aliases for all above formats (e.g., field as alias)
		"""
		...
	
	def parse_fields(self, fields: str | list | tuple | Field | AggregateFunction | None) -> list[Field | AggregateFunction | Criterion | DynamicTableField | ChildQuery]:
		...
	
	def apply_group_by(self, group_by: str | None = ...): # -> None:
		...
	
	def apply_order_by(self, order_by: str | None): # -> None:
		...
	
	def check_read_permission(self): # -> None:
		"""Check if user has read permission on the doctype"""
		...
	
	def apply_field_permissions(self): # -> list[Any]:
		"""Filter the list of fields based on permlevel."""
		...
	
	def get_user_permission_conditions(self, role_permissions): # -> tuple[list[Any], Literal[False]] | tuple[list[Any], Literal[True]]:
		"""Build conditions for user permissions and return tuple of (conditions, fetch_shared_docs)"""
		...
	
	def get_doctype_link_fields(self): # -> list[dict[str, str]]:
		...
	
	def add_permission_conditions(self): # -> None:
		...
	
	def get_permission_query_conditions(self): # -> list[Any]:
		"""Add permission query conditions from hooks and server scripts"""
		...
	
	def get_permission_type(self, doctype) -> str:
		"""Get permission type (select/read) based on user permissions"""
		...
	
	def requires_owner_constraint(self, role_permissions): # -> Literal[True] | None:
		"""Return True if "select" or "read" isn't available without being creator."""
		...
	


class Permission:
	@classmethod
	def check_permissions(cls, query, **kwargs): # -> None:
		...
	
	@staticmethod
	def get_tables_from_query(query: str): # -> list[Any]:
		...
	


class DynamicTableField:
	def __init__(self, doctype: str, fieldname: str, parent_doctype: str, alias: str | None = ...) -> None:
		...
	
	def __str__(self) -> str:
		...
	
	@staticmethod
	def parse(field: str, doctype: str, allow_tab_notation: bool = ...): # -> ChildTableField | LinkTableField | None:
		...
	
	def apply_select(self, query: QueryBuilder) -> QueryBuilder:
		...
	


class ChildTableField(DynamicTableField):
	def __init__(self, doctype: str, fieldname: str, parent_doctype: str, parent_fieldname: str | None = ..., alias: str | None = ...) -> None:
		...
	
	def apply_select(self, query: QueryBuilder) -> QueryBuilder:
		...
	
	def apply_join(self, query: QueryBuilder) -> QueryBuilder:
		...
	


class LinkTableField(DynamicTableField):
	def __init__(self, doctype: str, fieldname: str, parent_doctype: str, link_fieldname: str, alias: str | None = ...) -> None:
		...
	
	def apply_select(self, query: QueryBuilder) -> QueryBuilder:
		...
	
	def apply_join(self, query: QueryBuilder) -> QueryBuilder:
		...
	


class ChildQuery:
	def __init__(self, fieldname: str, fields: list, parent_doctype: str) -> None:
		...
	
	def get_query(self, parent_names=...) -> QueryBuilder:
		...
	


def get_nested_set_hierarchy_result(doctype: str, name: str, hierarchy: str) -> list[str]:
	"""Get matching nodes based on operator."""
	...

class RawCriterion(Term):
	"""A class to represent raw SQL string as a criterion.

	Allows using raw SQL strings in pypika queries:
		frappe.qb.from_("DocType").where(RawCriterion("name like 'a%'"))
	"""
	def __init__(self, sql_string: str) -> None:
		...
	
	def get_sql(self, **kwargs: Any) -> str:
		...
	
	def __and__(self, other): # -> CombinedRawCriterion:
		...
	
	def __or__(self, other): # -> CombinedRawCriterion:
		...
	
	def __invert__(self): # -> RawCriterion:
		...
	


class CombinedRawCriterion(RawCriterion):
	def __init__(self, left, right, operator) -> None:
		...
	
	def get_sql(self, **kwargs: Any) -> str:
		...
	


class SQLFunctionParser:
	"""Parser for SQL function dictionaries in query builder fields."""
	def __init__(self, engine) -> None:
		...
	
	def is_function_dict(self, field_dict: dict) -> bool:
		"""Check if a dictionary represents a SQL function definition."""
		...
	
	def parse_function(self, function_dict: dict) -> Field:
		"""Parse a SQL function dictionary into a pypika function call."""
		...
	


