"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document
from tenacity import retry, retry_if_exception_type, stop_after_attempt

class AccessLog(Document):
    if TYPE_CHECKING:
        columns: DF.HTMLEditor | None
        export_from: DF.Data | None
        file_type: DF.Data | None
        filters: DF.Code | None
        method: DF.Data | None
        page: DF.HTMLEditor | None
        reference_document: DF.Data | None
        report_name: DF.Data | None
        timestamp: DF.Datetime | None
        user: DF.Link | None
        ...
    @staticmethod
    def clear_old_logs(days=...):  # -> None:
        ...

@frappe.whitelist()
@frappe.write_only()
@retry(stop=stop_after_attempt(3), retry=retry_if_exception_type(frappe.DuplicateEntryError), reraise=True)
def make_access_log(
    doctype=..., document=..., method=..., file_type=..., report_name=..., filters=..., page=..., columns=...
):  # -> None:
    ...

_make_access_log = ...
