"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class EmailTemplate(Document):
    if TYPE_CHECKING:
        response: DF.TextEditor | None
        response_html: DF.Code | None
        subject: DF.Data
        use_html: DF.Check
        ...
    @property
    def response_(self):  # -> Code | None:
        ...
    def validate(self):  # -> None:
        ...
    def get_formatted_subject(self, doc):  # -> str | Any | None:
        ...
    def get_formatted_response(self, doc):  # -> str | Any | None:
        ...
    def get_formatted_email(self, doc):  # -> dict[str, str | Any | None]:
        ...

@frappe.whitelist()
def get_email_template(template_name, doc):
    """Return the processed HTML of a email template with the given doc"""
    ...
