"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WebFormListColumn(Document):
	if TYPE_CHECKING:
		fieldname: DF.Literal[None]
		fieldtype: DF.Data | None
		label: DF.Data | None
		name: DF.Int | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		...


