"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class NavbarSettings(Document):
    if TYPE_CHECKING:
        announcement_widget: DF.TextEditor | None
        app_logo: DF.AttachImage | None
        help_dropdown: DF.Table[NavbarItem]
        settings_dropdown: DF.Table[NavbarItem]
        ...

def get_app_logo():  # -> Any:
    ...
def get_navbar_settings():  # -> Document:
    ...
def sync_standard_items():  # -> None:
    """Syncs standard items from hooks. Called in migrate"""
    ...

def sync_table(key, hook):  # -> None:
    ...
