"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WebsiteRouteRedirect(Document):
    if TYPE_CHECKING:
        parent: DF.Data
        parentfield: DF.Data
        parenttype: DF.Data
        redirect_http_status: DF.Literal[301, 302, 307, 308]
        source: DF.SmallText
        target: DF.SmallText
        ...
