"""
This type stub file was generated by pyright.
"""

import typing

from pypika import MySQLQuery, PostgreSQLQuery, SQLLiteQuery, terms
from pypika.dialects import MySQLQueryBuilder, PostgreSQLQueryBuilder, SQLLiteQueryBuilder
from pypika.queries import QueryBuilder, Schema, Table
from pypika.terms import Function

class Base:
    terms = terms
    desc = ...
    asc = ...
    Schema = Schema
    Table = Table
    if typing.TYPE_CHECKING:
        engine: Engine
        ...
    @staticmethod
    def functions(name: str, *args, **kwargs) -> Function: ...
    @staticmethod
    def DocType(table_name: str, *args, **kwargs) -> Table: ...
    @classmethod
    def into(cls, table, *args, **kwargs) -> QueryBuilder: ...
    @classmethod
    def update(cls, table, *args, **kwargs) -> QueryBuilder: ...

class MariaDB(Base, MySQLQuery):
    Field = terms.Field
    _BuilderClasss = MySQLQueryBuilder
    @classmethod
    def from_(cls, table, *args, **kwargs):  # -> QueryBuilder:
        ...

class Postgres(Base, PostgreSQLQuery):
    field_translation = ...
    schema_translation = ...
    _BuilderClasss = PostgreSQLQueryBuilder
    @classmethod
    def Field(cls, field_name, *args, **kwargs):  # -> Field:
        ...
    @classmethod
    def from_(cls, table, *args, **kwargs):  # -> QueryBuilder:
        ...

class SQLite(Base, SQLLiteQuery):
    Field = terms.Field
    _BuilderClasss = SQLLiteQueryBuilder
    @classmethod
    def from_(cls, table, *args, **kwargs):  # -> QueryBuilder:
        ...
