"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class AssignmentRuleDay(Document):
    if TYPE_CHECKING:
        day: DF.Literal[Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
        parent: DF.Data
        parentfield: DF.Data
        parenttype: DF.Data
        ...
