"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class QueryParameters(Document):
	if TYPE_CHECKING:
		key: DF.Data
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		value: DF.Data
		...


