"""
This type stub file was generated by pyright.
"""

import frappe

@frappe.whitelist(methods=["POST", "PUT"])
def savedocs(doc, action): # -> None:
	"""save / submit / update doclist"""
	...

@frappe.whitelist(methods=["POST", "PUT"])
def cancel(doctype=..., name=..., workflow_state_fieldname=..., workflow_state=...): # -> None:
	"""cancel a doclist"""
	...

@frappe.whitelist(methods=["POST", "PUT"])
def discard(doctype: str, name: str | int): # -> None:
	"""discard a draft document"""
	...

def send_updated_docs(doc): # -> None:
	...

def set_local_name(doc): # -> None:
	...

