"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document
from frappe.utils.caching import redis_cache

class WebPageView(Document):
	if TYPE_CHECKING:
		browser: DF.Data | None
		browser_version: DF.Data | None
		campaign: DF.Data | None
		content: DF.Data | None
		is_unique: DF.Data | None
		medium: DF.Data | None
		path: DF.Data | None
		referrer: DF.Data | None
		source: DF.Data | None
		time_zone: DF.Data | None
		user_agent: DF.Data | None
		visitor_id: DF.Data | None
		...
	@staticmethod
	def clear_old_logs(days=...): # -> None:
		...
	


@frappe.whitelist(allow_guest=True)
def make_view_log(referrer=..., browser=..., version=..., user_tz=..., source=..., campaign=..., medium=..., content=..., visitor_id=...): # -> None:
	...

@frappe.whitelist()
@redis_cache(ttl=5 * 60)
def get_page_view_count(path):
	...

def is_tracking_enabled(): # -> Any | None:
	...

