"""
This type stub file was generated by pyright.
"""

import logging

import frappe
from frappe.deprecation_dumpster import (
    get_tests_CompatFrappeTestCase,
)
from frappe.deprecation_dumpster import (
    tests_change_settings as change_settings,
)
from frappe.deprecation_dumpster import (
    tests_debug_on as debug_on,
)
from frappe.deprecation_dumpster import (
    tests_patch_hooks as patch_hooks,
)
from frappe.deprecation_dumpster import (
    tests_timeout as timeout,
)
from frappe.deprecation_dumpster import (
    tests_utils_get_dependencies as get_dependencies,
)

from .generators import *

logger = ...

def check_orpahned_doctypes():  # -> None:
    """Check that all doctypes in DB actually exist after patch test"""
    ...

def toggle_test_mode(enable: bool):  # -> None:
    """Enable or disable `frappe.in_test` (and related deprecated flag)"""
    ...

FrappeTestCase = ...
