"""
This type stub file was generated by pyright.
"""

import logging
import frappe
from .generators import *
from frappe.deprecation_dumpster import get_tests_CompatFrappeTestCase, tests_change_settings as change_settings, tests_debug_on as debug_on, tests_patch_hooks as patch_hooks, tests_timeout as timeout, tests_utils_get_dependencies as get_dependencies

logger = ...
def check_orpahned_doctypes(): # -> None:
	"""Check that all doctypes in DB actually exist after patch test"""
	...

def toggle_test_mode(enable: bool): # -> None:
	"""Enable or disable `frappe.in_test` (and related deprecated flag)"""
	...

FrappeTestCase = ...
