"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class GlobalSearchSettings(Document):
	if TYPE_CHECKING:
		allowed_in_global_search: DF.Table[GlobalSearchDocType]
		...
	def validate(self): # -> None:
		...
	


def get_doctypes_for_global_search(): # -> Any | None:
	...

@frappe.whitelist()
def reset_global_search_settings_doctypes(): # -> None:
	...

def update_global_search_doctypes(): # -> None:
	...

def show_message(progress, msg): # -> None:
	...

