"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Mapping, Sequence
from datetime import date, datetime
from typing import NamedTuple, Self, TypeAlias, TypeGuard, TypeVar, override

from pypika import Column

type Doct = str
type Fld = str
type Op = str
type DateTime = datetime | date
type _Value = str | int | float | None | DateTime | Column
type _InputValue = _Value | bool
type Value = _Value | Sequence[_Value]
type InputValue = _InputValue | Sequence[_InputValue]
type FilterTupleSpec = tuple[Fld, InputValue] | tuple[Fld, Op, InputValue] | tuple[Doct, Fld, Op, InputValue]
type FilterMappingSpec = Mapping[Fld, _InputValue | tuple[Op, InputValue]]

class Sentinel:
    def __bool__(self) -> bool: ...
    @override
    def __str__(self) -> str: ...

UNSPECIFIED = ...
T = TypeVar("T")

def is_unspecified(value: T | Sentinel) -> TypeGuard[Sentinel]: ...

class _FilterTuple(NamedTuple):
    doctype: Doct
    fieldname: Fld
    operator: Op
    value: Value
    ...

class FilterTuple(_FilterTuple):
    """A named tuple representing a filter condition."""
    def __new__(
        cls,
        s: FilterTupleSpec | None = ...,
        /,
        *,
        doctype: Doct | Sentinel = ...,
        fieldname: Fld | Sentinel = ...,
        operator: Op = ...,
        value: InputValue | Sentinel = ...,
    ) -> Self:
        """
        Create a new FilterTuple instance.
        Args:
                s: A sequence representing the filter tuple.
                doctype: The document type.
                fieldname: The field name.
                operator: The comparison operator.
                value: The value to compare against.
        Returns:
                A new FilterTuple instance.
        """
        ...

    @override
    def __str__(self) -> str: ...

class Filters(list[FilterTuple]):
    """A sequence of filter tuples representing multiple filter conditions."""
    def __init__(
        self,
        /,
        *s: FilterTuple
        | FilterTupleSpec
        | FilterMappingSpec
        | Sequence[FilterTuple | FilterTupleSpec | FilterMappingSpec],
        doctype: Doct | Sentinel = ...,
    ) -> None:
        """
        Create a new Filters instance.

        Args:
                s: A sequence of FilterTuple or FilterTupleSpec, or a FilterMappingSpec.
                doctype: The document type for the filters.

        Returns:
                A new Filters instance.
        """
        ...

    @override
    def extend(
        self,
        values: Iterable[FilterTuple | FilterTupleSpec | FilterMappingSpec],
        doctype: Doct | Sentinel = ...,
    ) -> None: ...
    @override
    def append(
        self, value: FilterTuple | FilterTupleSpec | FilterMappingSpec, doctype: Doct | Sentinel = ...
    ) -> None: ...
    def optimize(self) -> None:
        """Optimize the filters by grouping '=' operators into 'in' operators where possible."""
        ...

    @override
    def __str__(self) -> str: ...

type FilterSignature = Filters | FilterTuple | FilterMappingSpec | FilterTupleSpec
