"""
This type stub file was generated by pyright.
"""

import frappe

def publish_progress(percent, title=..., doctype=..., docname=..., description=..., task_id=...): # -> None:
	...

def publish_realtime(event: str | None = ..., message: dict | None = ..., room: str | None = ..., user: str | None = ..., doctype: str | None = ..., docname: str | None = ..., task_id: str | None = ..., after_commit: bool = ...): # -> None:
	"""Publish real-time updates

	:param event: Event name, like `task_progress` etc. that will be handled by the client (default is `task_progress` if within task or `global`)
	:param message: JSON message object. For async must contain `task_id`
	:param room: Room in which to publish update (default entire site)
	:param user: Transmit to user
	:param doctype: Transmit to doctype, docname
	:param docname: Transmit to doctype, docname
	:param after_commit: (default False) will emit after current transaction is committed"""
	...

def flush_realtime_log(): # -> None:
	...

def clear_realtime_log(): # -> None:
	...

def emit_via_redis(event, message, room): # -> None:
	"""Publish real-time updates via redis

	:param event: Event name, like `task_progress` etc.
	:param message: JSON message object. For async must contain `task_id`
	:param room: name of the room"""
	...

@frappe.whitelist(allow_guest=True)
def has_permission(doctype: str, name: str) -> bool:
	...

@frappe.whitelist(allow_guest=True)
def get_user_info(): # -> dict[str, Any]:
	...

def get_doctype_room(doctype): # -> str:
	...

def get_doc_room(doctype, docname): # -> str:
	...

def get_user_room(user): # -> str:
	...

def get_site_room(): # -> Literal['all']:
	...

def get_task_progress_room(task_id): # -> str:
	...

def get_website_room(): # -> Literal['website']:
	...

