"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class InvalidAppOrder(frappe.ValidationError):
	...


class InstalledApplications(Document):
	if TYPE_CHECKING:
		installed_applications: DF.Table[InstalledApplication]
		...
	def update_versions(self): # -> None:
		...
	
	def get_app_wise_setup_details(self): # -> _dict[Any, Any]:
		"""Get app wise setup details from the Installed Application doctype"""
		...
	
	def reload_doc_if_required(self): # -> None:
		...
	


@frappe.whitelist()
def update_installed_apps_order(new_order: list[str] | str): # -> None:
	"""Change the ordering of `installed_apps` global

	This list is used to resolve hooks and by default it's order of installation on site.

	Sometimes it might not be the ordering you want, so thie function is provided to override it.
	"""
	...

@frappe.whitelist()
def get_installed_app_order() -> list[str]:
	...

@frappe.request_cache
def get_setup_wizard_completed_apps(): # -> list[Any]:
	"""Get list of apps that have completed setup wizard"""
	...

@frappe.request_cache
def get_setup_wizard_not_required_apps(): # -> list[Any]:
	"""Get list of apps that do not require setup wizard"""
	...

@frappe.request_cache
def get_apps_with_incomplete_dependencies(current_app):
	"""Get apps with incomplete dependencies."""
	...

@frappe.request_cache
def get_setup_wizard_pending_apps(apps=...): # -> list[Any]:
	"""Get list of apps that have completed setup wizard"""
	...

