"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.utils.caching import request_cache

def get_report_doc(report_name): # -> Document:
	...

def get_report_result(report, filters): # -> None:
	...

@frappe.read_only()
def generate_report_result(report, filters=..., user=..., custom_columns=..., is_tree=..., parent_field=...): # -> dict[str, Any]:
	...

def normalize_result(result, columns): # -> list[Any]:
	...

@frappe.whitelist()
def get_script(report_name): # -> dict[str, Any]:
	...

def get_reference_report(report):
	...

@frappe.whitelist()
@frappe.read_only()
def run(report_name, filters=..., user=..., ignore_prepared_report=..., custom_columns=..., is_tree=..., parent_field=..., are_default_filters=...):
	...

def add_custom_column_data(custom_columns, result):
	...

def get_prepared_report_result(report, filters, dn=..., user=...): # -> dict[str, Any | list[Any]]:
	...

@frappe.whitelist()
def export_query(): # -> None:
	"""export from query reports"""
	...

def valid_report_name(report_name, suffix): # -> bool:
	...

def format_fields(data: frappe._dict) -> None:
	...

def build_xlsx_data(data, visible_idx, include_indentation, include_filters=..., ignore_visible_idx=..., include_hidden_columns=...): # -> tuple[list[Any], list[Any]]:
	...

def add_total_row(result, columns, meta=..., is_tree=..., parent_field=...):
	...

@frappe.whitelist()
def get_data_for_custom_field(doctype, field, names=...): # -> _dict[Any, Any]:
	...

def get_data_for_custom_report(columns, result): # -> dict[Any, Any]:
	...

@frappe.whitelist()
def save_report(reference_report, report_name, columns, filters): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | Data | None:
	...

def get_filtered_data(ref_doctype, columns, data, user): # -> list[Any]:
	...

def has_match(row, linked_doctypes, doctype_match_filters, ref_doctype, if_owner, columns_dict, user): # -> bool:
	"""Return True if after evaluating permissions for each linked doctype:
	        - There is an owner match for the ref_doctype
	        - `and` There is a user permission match for all linked doctypes

	Return True if the row is empty.

	Note:
	Each doctype could have multiple conflicting user permission doctypes.
	Hence even if one of the sets allows a match, it is true.
	This behavior is equivalent to the trickling of user permissions of linked doctypes to the ref doctype.
	"""
	...

@request_cache
def has_unrestricted_read_access(doctype, user): # -> bool:
	...

def get_linked_doctypes(columns, data): # -> dict[Any, Any]:
	...

def get_columns_dict(columns): # -> _dict[Any, Any]:
	"""Return a dict with column docfield values as dict.

	The keys for the dict are both idx and fieldname,
	so either index or fieldname can be used to search for a column's docfield properties.
	"""
	...

def get_column_as_dict(col): # -> _dict[Any, Any]:
	...

def get_user_match_filters(doctypes, user): # -> dict[Any, Any]:
	...

def validate_filters_permissions(report_name, filters=..., user=...): # -> None:
	...

def translate_report_data(data, total_row):
	...

