"""
This type stub file was generated by pyright.
"""

import frappe
from functools import lru_cache

"""build query for doclistview and return results"""
DISALLOWED_PARAMS = ...
@frappe.whitelist()
@frappe.read_only()
def get(): # -> dict[str, Any] | list[Any]:
	...

@frappe.whitelist()
@frappe.read_only()
def get_list(): # -> list[Any]:
	...

@frappe.whitelist()
@frappe.read_only()
def get_count() -> int | None:
	...

def execute(doctype, *args, **kwargs): # -> list[Any]:
	...

def get_form_params(): # -> _dict[Any, Any]:
	"""parse GET request parameters."""
	...

def validate_args(data):
	...

def validate_fields(data): # -> None:
	...

def validate_filters(data, filters): # -> None:
	...

def setup_group_by(data): # -> None:
	"""Add columns for aggregated values e.g. count(name)"""
	...

def raise_invalid_field(fieldname): # -> None:
	...

def is_standard(fieldname): # -> bool:
	...

@lru_cache(maxsize=1024)
def extract_fieldnames(field): # -> list[Any] | list[str]:
	...

def get_meta_and_docfield(fieldname, data): # -> tuple[_Meta, Any | None]:
	...

def update_wildcard_field_param(data): # -> bool:
	...

def clean_params(data): # -> None:
	...

def parse_json(data): # -> None:
	...

def get_parenttype_and_fieldname(field, data): # -> tuple[Any, Any]:
	...

def compress(data, args=...): # -> dict[str, Any]:
	"""separate keys and values"""
	...

@frappe.whitelist(methods=["POST", "PUT"])
def save_report(name, doctype, report_settings): # -> Data | None:
	"""Save reports of type Report Builder from Report View"""
	...

@frappe.whitelist(methods=["POST", "DELETE"])
def delete_report(name): # -> None:
	"""Delete reports of type Report Builder from Report View"""
	...

@frappe.whitelist()
@frappe.read_only()
def export_query(): # -> None:
	"""export from report builder"""
	...

def append_totals_row(data): # -> list[Any]:
	...

def get_field_info(fields, doctype): # -> list[Any]:
	"""Get column names, labels, field types, and translatable properties based on column names."""
	...

def handle_duration_fieldtype_values(doctype, data, fields):
	...

def parse_field(field: str) -> tuple[str | None, str]:
	"""Parse a field into parenttype and fieldname."""
	...

@frappe.whitelist(methods=["POST", "DELETE"])
def delete_items(): # -> None:
	"""delete selected items"""
	...

def delete_bulk(doctype, items): # -> None:
	...

@frappe.whitelist()
@frappe.read_only()
def get_sidebar_stats(stats, doctype, filters=...): # -> dict[str, Any | dict[Any, Any]]:
	...

@frappe.whitelist()
@frappe.read_only()
def get_stats(stats, doctype, filters=...): # -> dict[Any, Any]:
	"""get tag info"""
	...

@frappe.whitelist()
def get_filter_dashboard_data(stats, doctype, filters=...): # -> dict[Any, Any]:
	"""get tags info"""
	...

def scrub_user_tags(tagcount): # -> list[list[Any]]:
	"""rebuild tag list for tags"""
	...

def get_match_cond(doctype, as_condition=...): # -> str | list[Any]:
	...

def build_match_conditions(doctype, user=..., as_condition=...): # -> str | list[Any]:
	...

def get_filters_cond(doctype, filters, conditions, ignore_permissions=..., with_match_conditions=...): # -> str:
	...

