"""
This type stub file was generated by pyright.
"""

from typing import NotRequired, TypedDict

import frappe

def sanitize_searchfield(searchfield: str):  # -> None:
    ...

class LinkSearchResults(TypedDict):
    value: str
    description: str
    label: NotRequired[str]
    ...

@frappe.whitelist()
def search_link(
    doctype: str,
    txt: str,
    query: str | None = ...,
    filters: str | dict | list | None = ...,
    page_length: int = ...,
    searchfield: str | None = ...,
    reference_doctype: str | None = ...,
    ignore_user_permissions: bool = ...,
) -> list[LinkSearchResults]: ...
@frappe.whitelist()
def search_widget(
    doctype: str,
    txt: str,
    query: str | None = ...,
    searchfield: str | None = ...,
    start: int = ...,
    page_length: int = ...,
    filters: str | None | dict | list = ...,
    filter_fields=...,
    as_dict: bool = ...,
    reference_doctype: str | None = ...,
    ignore_user_permissions: bool = ...,
):  # -> list[Any]:
    ...
def get_std_fields_list(meta, key):  # -> list[str]:
    ...
def build_for_autosuggest(res: list[tuple], doctype: str) -> list[LinkSearchResults]: ...
def scrub_custom_query(query, key, txt): ...
def relevance_sorter(key, query, as_dict):  # -> tuple[bool, str]:
    ...
@frappe.whitelist()
def get_names_for_mentions(search_term):  # -> list[Any]:
    ...
def get_users_for_mentions():  # -> list[Any]:
    ...
def get_user_groups():  # -> list[Any]:
    ...
@frappe.whitelist()
def get_link_title(
    doctype, docname
):  # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
    ...
