"""
This type stub file was generated by pyright.
"""

def validate_route_conflict(doctype, name):  # -> None:
    """
    Raises exception if name clashes with routes from other documents for /app routing
    """
    ...

def slug(name): ...
def pop_csv_params(form_dict):  # -> dict[str, Any]:
    """Pop csv params from form_dict and return them as a dict."""
    ...

def get_csv_bytes(data: list[list], csv_params: dict) -> bytes:
    """Convert data to csv bytes."""
    ...

def apply_csv_decimal_sep(data: list[list], decimal_sep: str) -> list[list]:
    """Apply decimal separator to csv data."""
    ...

def provide_binary_file(filename: str, extension: str, content: bytes) -> None:
    """Provide a binary file to the client."""
    ...
